languageCode = "en-gb"
title = "Port 22"
baseurl = "https://port22.co.uk/"
theme = "telnet"
keywords = "Port22, Security, News" # Not working
metaDataFormat = "yaml"
paginate = "50"
rssLimit = "10"
disqusShortname = "p22-1"


copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License unless otherwise stated."

# Menu Stuffs
SectionPagesMenu = "main"

## Hides these.
[[menu.main]]
	weight = 0
	identifier = "news"

[[menu.main]]
	weight = 0
	identifier = "guidelines"

## Specify the menu items.
[[menu.main]]
	name = "Home"
	weight = 1
	identifier = ""
	url = "/"

[[menu.main]]
	name = "Blog"
	weight = 2
	identifier = "blog"
	url = "/blog/"

[[menu.main]]
	name = "About"
	weight = 3
	identifier = "about"
	url = "/about/"

[author]
    name = "Port 22"
    email = "info@port22.co.uk"
